module.exports = Object.freeze({
  YOUTUBE: 'YOUTUBE',
  DRIBBBLE: 'DRIBBBLE',
  FACEBOOK: 'FACEBOOK',
  GITHUB: 'GITHUB',
  GOOGLEPLUS: 'GOOGLEPLUS',
  INSTAGRAM: 'INSTAGRAM',
  LINKEDIN: 'LINKEDIN',
  PINTREST: 'PINTREST',
  REDDIT: 'REDDIT',
  SNAPCHAT: 'SNAPCHAT',
  STEAM: 'STEAM',
  TUMBLR: 'TUMBLR',
  TWITCH: 'TWITCH',
  TWITTER: 'TWITTER',
  VIMEO: 'VIMEO',
  VK: 'VK',
  OTHER: 'OTHER'
});